CareMeClient/Controllers/BookingController.cs
using Core.Extensions;
using Data.Models;
using Data.ViewModels;
using Infra.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CareMeClient.Controllers
{
    public class BookingController : Controller
    {
      
        //Get Doctor Speciality List for Drop Down
        public async Task<ActionResult> Index()
        {
            DoctorSpecialitiesViewModel result = await DoctorApiRequestHelper.GetDocSpecialtyListFilter();
            return View(result);
        }

        //Get Doctor List By Schedule FromTime
        public async Task<ActionResult> DoctorListByTime(DateTime? fromtime = null, DateTime? totime = null, int pagesize = 0, int page = 0, int appointmentid=0, DateTime? date = null)
        {
            int hospitalid = Helper.CookieHelper.getstaffHospitalID();
            PagedListClient<tbDoctor> result = await BookingApiRequestHelper.DoctorListByTime(fromtime, totime,pagesize, page,hospitalid, appointmentid, date);
            return PartialView("_doctorListByScheduleTime", result);

        }

        //Get Appointment Schcedule Time by Schedule Date(Previous and Next)
        public async Task<ActionResult> AppointmentSchedule(DateTime? datetime = null, string type = null)
        {
            int hospitalid = Helper.CookieHelper.getstaffHospitalID();
            //   List<tbScheduleData> result = await DoctorApiRequestHelper.AppointmentSchedule(datetime, type);
            AppointScheduleViewModel result = await BookingApiRequestHelper.AppointmentSchedule(datetime, type, hospitalid);
            return PartialView("_scheduleTimeByDate", result);
        }

        //Get Doctor List By Schedule Date From Calender
        //public async Task<ActionResult> _doctor3listbyScheduleDate(DateTime? datetime = null, int pagesize = 5, int page = 1)
        //{
        //    PagedListClient<ScheduleDoctorViewModel> result = await Doctor3ApiRequestHelper.GetDoctorWithPaging(datetime, pagesize, page);
        //    return PartialView("_doctor3listbyScheduleDate", result);
        //}

        public async Task<ActionResult> _list(int docid = 0, int specialityid = 0, string docname = null, DateTime? datetime = null, DateTime? fromtime = null, DateTime? totime = null, int pagesize = 5, int page = 1)
        {
            int hospitalid = Helper.CookieHelper.getstaffHospitalID();
            PagedListClient<ScheduleBookingViewModel> result = await BookingApiRequestHelper.list(docid, specialityid, docname, datetime, fromtime, totime, pagesize, page,hospitalid);
            return PartialView("_list", result);
        }


        public async Task<ActionResult> getSpecialityList()
        {
            List<tbSpecialty> result = await DoctorApiRequestHelper.getSpecialityList();
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public async Task<ActionResult> _PatientForm(string FormType, int ID, int doctorid = 0, string doctorname = null, DateTime? appdate = null, DateTime? fromtime = null, DateTime? totime = null,int scheduleid=0)
        {
            ViewBag.doctorid = doctorid;
            ViewBag.doctorname = doctorname;
            ViewBag.appdate = appdate;
            ViewBag.fromtime = fromtime;
            ViewBag.totime = totime;
            ViewBag.scheduleid = scheduleid;
            tbPatient patient = new tbPatient();
            if (FormType == "Add")
            {
                return PartialView("_PatientForm", patient);
            }
            else
            {
                //tbPatient result = await BookingApiRequestHelper.GetPatientByID(ID);
                //return PartialView("_PatientForm", result);
                return null;
            }
        }

        public async Task<ActionResult> UpsertPatient(tbPatient patient, int doctorid = 0, string doctorname = null, DateTime? appdate = null, DateTime? fromtime = null, DateTime? totime = null, int scheduleid = 0)
        {
            PatientAppointmentViewModel shvm = new PatientAppointmentViewModel();
            shvm.appointment = new tbAppointment();
            shvm.appointment.DoctorId = doctorid;
            shvm.appointment.DoctorName = doctorname;
            string date = appdate.Value.ToShortDateString();
            string fromtimedate = fromtime.Value.ToShortTimeString();
            string appointmentdate = date + " " + fromtimedate;
            shvm.appointment.ScheduleDataID = scheduleid;
            shvm.appointment.AppointmentDateTime = DateTime.Parse(appointmentdate);
            shvm.appointment.HospitalId = CareMeClient.Helper.CookieHelper.getstaffHospitalID();
            //      shvm.appointment.HospitalName = CareMeClient.Helper.CookieHelper.getstaffHospitalName();

            shvm.patient = patient;
            PatientAppointmentViewModel result = await BookingApiRequestHelper.UpsertPatient(shvm);
            if (result != null)
            {
                if(result.patient != null)
                {
                    return Json("Success", JsonRequestBehavior.AllowGet);
                }
            }
            return Json("Fail", JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> _scheduleListbyDoctorID(int doctorid = 0, string docname = null, DateTime? date=null)
        {
            int hospitalid = Helper.CookieHelper.getstaffHospitalID();
            List<tbScheduleData> result = await BookingApiRequestHelper.scheduleListbyDoctorID(doctorid, docname, hospitalid, date);
            ViewBag.docid = doctorid;
            ViewBag.docname = docname;
            if(date != null)
            {
                ViewBag.Date = date.Value.Date;
            }
            else{
                ViewBag.Date = MyExtension.getLocalTime(DateTime.UtcNow);
            }
            
            return PartialView("_scheduleListbyDoctorID", result);
        }


    }
}

CareMeClient/Controllers/Doctor3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CareMeClient.Controllers
{
    public class Doctor3Controller : Controller
    {
        // GET: Doctor3
        public ActionResult Index()
        {
            return View();
        }
    }
}

CareMeClient/Views/Booking/_PatientForm.cshtml
@model Data.Models.tbPatient

@using (Html.BeginForm("UpsertPatient", "Doctor3", FormMethod.Post, new { id = "PatientForm" }))
{

    <div class="modal-header bg-blue">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
        <h4 class="modal-title">
            <img src="~/Content/Image/patient.png" width="50" height="50" style="border-radius:20px" />&nbsp;&nbsp; ADD NEW PATIENT
        </h4>
    </div>

        <input type="hidden" name="" id="doctorid" value="@ViewBag.doctorid" />
        <input type="hidden" name="" id="doctorname" value="@ViewBag.doctorname" />
        <input type="hidden" name="" id="appdate" value="@ViewBag.appdate" />
        <input type="hidden" name="" id="fromtime" value="@ViewBag.fromtime" />
        <input type="hidden" name="" id="totime" value="@ViewBag.totime" />
        <input type="hidden" name="" id="scheduleid" value="@ViewBag.scheduleid" />

        <div class="modal-body" id="mb">
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-6">
                        <label>Name</label>&nbsp;<span class="text-danger">*</span>
                        @Html.TextBoxFor(a => a.Name, new { placeholder = "", @class = "form-control", @required = "required" })

                    </div>
                    <div class="col-sm-6">
                        <label>Phone</label>&nbsp;<span class="text-danger">*</span>
                        @Html.TextBoxFor(a => a.Phone, new { placeholder = "", @class = "form-control", @required = "required" })

                    </div>
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-6">
                        <label>Age</label>&nbsp;<span class="text-danger">*</span>
                        @Html.TextBoxFor(a => a.Age, new { placeholder = "", @class = "form-control", @required = "required" })

                    </div>
                    <div class="col-sm-6">
                        <label>Gender</label>&nbsp;<span class="text-danger">*</span>
                        @{ var type = new List<SelectListItem>() {
                                       new SelectListItem {Value="", Text="-- Select --" },
                                       new SelectListItem {Value="Female", Text="Female" },
                                       new SelectListItem {Value="Male", Text="Male" }
                                    };
                        }
                        @Html.DropDownListFor(a => a.Gender, type, new { @class = "form-control", name = "select", @required = "required" })

                    </div>
                </div>
            </div>
            <br />

            <div class="row">
                <div class="col-sm-12">
                   <div class="col-sm-12">
                       <label>Address</label>&nbsp;<span class="text-danger">*</span>
                       @Html.TextAreaFor(a => a.Address, new { placeholder = "", @class = "form-control", @required = "required" })
                   </div>
                </div>
            </div>
            <br />
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-12">
                        <label>Problem</label>&nbsp;<span class="text-danger">*</span>
                        @Html.TextAreaFor(a => a.Problem, new { placeholder = "", @class = "form-control", @required = "required" })
                    </div>
                </div>
            </div>
          
        </div>
        @Html.HiddenFor(m => m.ID)
                        @Html.HiddenFor(m => m.Photo)
                        @Html.HiddenFor(m => m.IsDeleted)
                        @Html.HiddenFor(m => m.Accesstime)


                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="col-sm-12">
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default btn-rounded" data-dismiss="modal">Cancel</button>
                                            <button type="submit" class="btn btn-primary btn-rounded" id=""><span class="icon-add"></span> Save</button>
                                        </div>
                                    </div>

                                </div>

                            </div>

                      
                        }

CareMeClient/Views/Booking/_doctorListByScheduleTime.cshtml
@model Data.ViewModels.PagedListClient<Data.Models.tbDoctor>
@using PagedList;
@using PagedList.Mvc;


        @{

            if (Model.TotalCount > 0)
            {


                <div id="list_Binder">
                    @foreach (var list in Model.Results)
                    {
                        <div class="panel-custom-default pa-10 mt-5" id="div_Doctor_@list.ID">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="col-sm-2">
                                        <span><img src="@list.PhotoUrl" style="width: 80px; height: 80px;" /></span>
                                    </div>

                                    <div class="col-sm-2">
                                        <h6 class="lh15">@list.Name</h6>
                                        <span class="lh10 text-muted">Name</span>
                                    </div>
                                    <div class="col-sm-2">
                                        <h6 class="lh15">@list.Specialty</h6>
                                        <span class="lh10 text-muted">Specialty</span>
                                    </div>

                                    <div class="col-sm-3">
                                        <h6 class="lh15">@list.Qualification</h6>
                                        <span class="lh10 text-muted">Qualification</span>
                                    </div>
                                    <div class="col-md-3 pull-right">
                                        <span class="glyphicon glyphicon-chevron-down" id="button-right" data-doctorID="@list.ID" data-doctorname="@list.Name" onclick="ScheduleListByDoctor(this)"></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="panel-custom-default pa-10 mt-5" id="div_schedulebydoctor_@list.ID" style="display:none!important">
                            <div class="div_schedulebydoctor_@list.ID">

                            </div>
                        </div>
                    }
                </div>
                <br />
                <div class="col-md-12">
                    <div class="pagedList" style="text-align:center">
                        @Html.PagedListPager(Model.Results, page => Url.Action("DoctorListByTime", "Doctor3",
 new { page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
                    </div>
                </div>
            }
            else
            {
                <div class="panel-custom-default pa-10 mt-5">
                    <div class="row">
                        <div class="col-md-12" style="text-align:center">
                            <h4>There is no search doctor list</h4>
                            <h6>Add a new doctor.....</h6><button class="btn btn-primary btn-xs btn-rounded" onclick="addDoctor()">Add Doctor</button>
                        </div>
                    </div>
                </div>
            }
        }

CareMeClient/Views/Booking/_list.cshtml
@model Data.ViewModels.PagedListClient<Data.ViewModels.ScheduleBookingViewModel>
@using PagedList;
@using PagedList.Mvc;


@{

    if (Model.TotalCount > 0)
    {


        <div id="list_Binder">
            @foreach (var list in Model.Results)
            {
                <div class="panel-custom-default pa-10 mt-5" id="div_Doctor_@list.doctor.ID">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-sm-2">
                                <span><img src="@list.doctor.PhotoUrl" style="width: 80px; height: 80px;" /></span>
                            </div>

                            <div class="col-sm-3">
                                <h6 class="lh20 zawgyi_text">@list.doctor.Name</h6>
                                <span class="lh20 text-muted zawgyi_text">@list.doctor.Specialty</span>
                            </div>
                           
                           
                            <div class="col-sm-6">
                                <h6 class="lh20 zawgyi_text">@list.doctor.Qualification</h6>
                                <span class="lh20 text-muted zawgyi_text">Qualification</span>
                            </div>
                            <div class="col-md-1 pull-right">
                              <span class="glyphicon glyphicon-chevron-down" id="button-right" data-doctorID="@list.doctor.ID" data-doctorname="@list.doctor.Name" onclick="ScheduleListByDoctor(this)"></span>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel-custom-default pa-10 mt-5" id="div_schedulebydoctor_@list.doctor.ID" style="display:none!important">
                    <div class="div_schedulebydoctor_@list.doctor.ID">

                    </div>
                </div>
            }
        </div>
        <br />
        <div class="col-md-12">
            <div class="pagedList" style="text-align:center">
                @Html.PagedListPager(Model.Results, page => Url.Action("_doctor3list", "Doctor3",
 new { page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
            </div>
        </div>
    }
    else
    {
        <div class="panel-custom-default pa-10 mt-5">
            <div class="row">
                <div class="col-md-12" style="text-align:center">
                    <h4>There is no search doctor list</h4>
                    <h6>Add a new doctor.....</h6><button class="btn btn-primary btn-xs btn-rounded" onclick="addDoctor()">Add Doctor</button>
                </div>
            </div>
        </div>
    }
}

CareMeClient/Views/Booking/_scheduleListbyDoctorID.cshtml
@model List<Data.Models.tbScheduleData>

   <table class="table" width="100%">
        <thead>
            <tr>
                @{
                        var today = ViewBag.Date;  //Core.Extensions.MyExtension.getLocalTime(DateTime.UtcNow).Date;
                        for (var i = 0; i < 5; i++)
                        {
                        <th class="mr-10">
                            <text>@today.AddDays(i).ToString("dd MMM yyyy")</text>
                        </th>
                    }
                }
            </tr>

        </thead>
        <tbody>
            <tr>
                @{
                    var today_bd = @today; //Core.Extensions.MyExtension.getLocalTime(DateTime.UtcNow).Date;
                }
                @for (var i = 0; i < 5; i++)
                {
                    var fromdate = today_bd.AddDays(i).Date;
                    var todate = today_bd.AddDays(i + 1).Date;

                    var schdata = Model.Where(a => a.AppointmentDatetime >= fromdate && a.AppointmentDatetime < todate).ToList();
                    if (schdata.Count > 0)
                    {
                        <td class="mr-5" style="vertical-align: top!important;">
                            @foreach (var item in schdata)
                            {
                                <div class="panel-custom-default" style="margin-bottom:4px;padding:3px;text-align:center;background-color:#f6ebeb!important">

                                    <div class="row">
                                        <div class="col-xs-12">

                                            <span>@item.Fromtime.Value.ToShortTimeString()</span><span> -</span>
                                            <span>@item.Totime.Value.ToShortTimeString()</span>
                                        </div>

                                        <div class="mt-20" style="text-align:center">
                                            @*<button class="btn btn-primary btn-xs btn-rounded pull-left" data-appdate="@item.AppointmentDatetime" data-fromtime="@item.Fromtime" data-totime="@item.Totime" data-doctorid="@item.ID" data-doctorname="@item.DoctorName" onclick="addPatient(this)">Book Now</button>*@
                                         
                                               <a class="" date-scheduleid="@item.ID" data-appdate="@item.AppointmentDatetime" data-fromtime="@item.Fromtime" data-totime="@item.Totime" data-doctorid="@item.DoctorID" data-doctorname="@item.DoctorName" onclick="addPatient(this)">Book Now</a>
                                        </div>

                                    </div>
                                </div>

                            }
                        </td>
                    }
                    else
                    {
                        <td class="mr-5"> </td>   }
                }
            </tr>

        </tbody>
    </table>
                    

CareMeClient/Views/Booking/_scheduleTimeByDate.cshtml
@model Data.ViewModels.AppointScheduleViewModel

<head>
    <style>

   button
    {
    border:none;
    }
    </style>
   
</head>
  

        <h4 style="text-align:center">Appointment Date</h4>
        <div id="myCarousel" class="carousel slide mt-10" style="margin-bottom:30px" data-ride="carousel">

            <div class="carousel-inner" id="inner-text">
                <div class="item active" id="text1" style="font-size:14px;font-weight:bold">
                   @if (Model.appointDatetime != null)
                   {
                   @Model.appointDatetime.Value.ToString("dd MMM yyyy")
                   }
                
                </div>

            </div>
            @*<a class="left carousel-control" href="#myCarousel" data-slide="prev" style="background-image:none;">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>

            <a class="right carousel-control" href="#myCarousel" data-slide="next" style="background-image:none;">
                <span class="glyphicon glyphicon-chevron-right"></span>

            </a>*@
            @*<button data-appdate="@Model.appointDatetime" onclick="prev(this)" class="left carousel-control" data-slide="prev" style="background-image:none;">
                <span class="glyphicon glyphicon-chevron-left"></span>
                
            </button>
            <button data-appdate="@Model.appointDatetime" onclick="next(this)" class="right carousel-control" data-slide="next" style="background-image:none;">
                <span class="glyphicon glyphicon-chevron-right"></span>
                
            </button>*@
            @if (Model.appointDatetime != null)
            {
                <span type="button" data-appdate="@Model.appointDatetime" data-appdate1="@Model.appointDatetime.Value.AddDays(-1)" onclick="prev(this)" class="left carousel-control " data-slide="prev" style="background-image:none;">
                    <span class="glyphicon glyphicon-chevron-left"></span>

                </span>
                <span type="button" data-appdate="@Model.appointDatetime" data-appdate1="@Model.appointDatetime.Value.AddDays(1)" onclick="next(this)" class="right carousel-control " data-slide="next" style="background-image: none;">
                    <span class="glyphicon glyphicon-chevron-right"></span>

                </span>
            }

          

        </div>
@foreach (var list in Model.scheduledatas.OrderBy(a=>a.Fromtime))
{

        <div class="" align="center"> 
            <a onclick="DoctorListByTime(this)" data-fromtime="@list.Fromtime" data-appointmentID="@list.ID" data-totime="@list.Totime"
               class="btn btn-danger btn-lg btn-rounded btn-block" id="btn">@list.Fromtime.Value.ToShortTimeString() - @list.Totime.Value.ToShortTimeString()</a>
        </div>


}
        


       