CareMeClient/Controllers/HistoryController.cs
using CareMeClient.Helper;
using Data.Models;
using Data.ViewModels;
using Infra.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CareMeClient.Controllers
{
    public class HistoryController : Controller
    {
        // GET: History
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> _historylist(string name = null, DateTime? datetime = null, int pagesize = 10, int page = 1)
        {
            int hospitalid = CookieHelper.getstaffHospitalID();
            PagedListClient<tbAppointment> result = await HistoryApiRequestHelper.GetAppointmentHistoryListWithPaging(name, datetime, pagesize, page, hospitalid);
            return PartialView("_historylist", result);
        }
    }
}

CareMeClient/Views/History/Index.cshtml
<div class="mt-20">
    <div class="navbar  navbar-component fs14" style="position: relative; z-index: 18;">


        @*<div class="navbar-header">       
            <button class="btn btn-default mt-5 btnr5" onclick="statusFilter('')">All</button>   
            <button class="btn btn-default mt-5 btnr5" onclick="statusFilter('CANCEL')">CANCEL</button>
            <button class="btn btn-default mt-5 btnr5" onclick="statusFilter('CHECKOUT')">CHECKOUT</button>
        </div>*@        


        <div class="navbar-collapse collapse" id="navbar-form-select2">
            <form class="navbar-form navbar-right">
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for..." name="q" id="txt_itemName">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button" onclick="Search()">Go!</button>
                        </span>
                    </div><!-- /input-group -->

                </div>
            </form>
            <div class="col-md-3" style="float:right">

                <div class="input-group">

                    <input type="text" class="form-control daterange-single" id="datetime" value="">
                    <span class="input-group-addon"><i class="icon-calendar22"></i></span>
                </div>
            </div>
        </div>
        <div id="div_List">
            <div id="loading" style="text-align:center">
                <img src="~/Content/Image/Spinner-1s-200px.gif" width="200" height="200" />
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        var page = 1;
        var pagesize = 10;
        var name;
        var status;
        var doctorname;
        var datetime;
        $(function () {
            LoadHistoryList();
            initPaging();

            $('.daterange-single').daterangepicker({
                singleDatePicker: true
            });


        });


        function initPaging() {
            $("#div_List").on("click", ".pagedList a", function (e) {
                e.preventDefault();
                var $a = $(this).attr("href");
                try {
                    var pageurl = $a.split(/=/);
                    page = pageurl[1];
                    if (page == null) {
                        page = 1;
                    }
                }
                catch (e) {
                    page = 1;
                }
                LoadMainList();
            });
        }

        function statusFilter(e) {
            status = e;
            Search();
        }

        function Search() {
            name = $('#txt_itemName').val();
            datetime = $('#datetime').val();
            LoadHistoryList();
        }


         function LoadHistoryList() {
            $('#loading').show();
            $.ajax({
                cache: false,
                url: '@Url.Action("_historylist", "History")',
                data: { name: name, datetime: datetime, pagesize: pagesize, page: page },
                beforeSend: function () {

                },
                success: function (result) {
                    $('#div_List').empty().append(result);
                },
                complete: function () {
                    $('#loading').hide();
                    $('#txt_itemName').val("");
                    $('#datetime').val("");
                }
            });
        }



    </script>
}

CareMeClient/Views/History/_historyList.cshtml
@model Data.ViewModels.PagedListClient<Data.Models.tbAppointment>
@using PagedList;
@using PagedList.Mvc;
@{
    if (Model.TotalCount > 0)
    {
        <div id="list_Binder">
            @foreach (var list in Model.Results)
            {
                <div class="panel-custom-default pa-10 mt-20" id="div_statuscancel">
                    <div class="row">

                        <div class="col-md-12">

                            <div class="col-md-2">
                                <span style="padding-top:10px"><img src="~/Content/Image/patient.png" style="width: 80px; height: 80px;" /></span>
                            </div>
                            <div class="col-md-2">
                                <h6 class="zawgyi_text ml-15">@list.PatientName</h6>
                                <span class="zawgyi_text ml-15">@list.PatientAge yrs</span>

                            </div>


                            <div class="col-md-2">
                                <h6 class="zawgyi_text">@list.DoctorName</h6>

                            </div>

                            <div class="col-md-4">
                                <h6 class="zawgyi_text">Appointment : @list.AppointmentDateTime.Value.ToString("dd MMM yyyy") @list.AppointmentDateTime.Value.ToShortTimeString()</h6>
                            </div>

                            <div class="col-md-2">
                                <span class="">
                                    <span class="text-success" data-status="ACCEPTED" data-id="">Booking No : </span>
                                    <a href="#" class="btn border-success text-success btn-flat btn-rounded btn-icon" onclick="newstatusChange(this)" data-status="CHECKIN" data-id="@list.ID">@list.Counter</a>
                                </span>
                            </div>






                        </div>
                    </div>
                </div>
            }
        </div>
        <br /><br />
                <div class="col-md-12">
                    <div class="pagedList" style="text-align:center">
                        @Html.PagedListPager(Model.Results, page => Url.Action("_historylist", "History",
                                          new { page }), PagedListRenderOptions.ClassicPlusFirstAndLast)
                    </div>
                </div>
    }
    else
    {
        <div class="panel-custom-default pa-10 mt-20">
            <div class="row">
                <div class="col-md-12">
                    <h4 style="text-align:center">......There is no history list......</h4>
                </div>
            </div>
        </div>
    }
}