CareMeBotWeb/Controllers/AppointmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CareMeBotWeb.Controllers
{
    public class AppointmentController : Controller
    {
        // GET: Appointment
        public ActionResult Index(int doctorID= 1, string msgrid = null, string msgrname= null)
        {
            ViewBag.msgrid = msgrid;
            ViewBag.msgrname = msgrname;
            ViewBag.doctorID = doctorID;
            return View();
        }

        public ActionResult Success()
        {
            return View();
        }
    }
}

CareMeBotWeb/Controllers/BookingController.cs
using Data.Models;
using Data.ViewModels;
using Infra.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CareMeBotWeb.Controllers
{
    public class BookingController : Controller
    {
        // GET: Booking
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> UpsertPatient(tbPatient patient, int doctorid = 0, string doctorname = null,
            DateTime? appdate = null, DateTime? fromtime = null, DateTime? totime = null, int scheduleid = 0, int hospitalID=0)
        {
            PatientAppointmentViewModel shvm = new PatientAppointmentViewModel();
            shvm.appointment = new tbAppointment();
            shvm.appointment.DoctorId = doctorid;
            shvm.appointment.DoctorName = doctorname;
            string date = appdate.Value.ToShortDateString();
            string fromtimedate = fromtime.Value.ToShortTimeString();
            string appointmentdate = date + " " + fromtimedate;
            shvm.appointment.ScheduleDataID = scheduleid;
            shvm.appointment.AppointmentDateTime = DateTime.Parse(appointmentdate);
            shvm.appointment.HospitalId = hospitalID; //CareMeClient.Helper.CookieHelper.getstaffHospitalID();
            //      shvm.appointment.HospitalName = CareMeClient.Helper.CookieHelper.getstaffHospitalName();

            shvm.patient = patient;
            PatientAppointmentViewModel result = await BookingApiRequestHelper.UpsertPatient(shvm);
            if (result != null)
            {
                BookingSuccessModel bsm = new BookingSuccessModel();
                bsm.doctor = await DoctorApiRequestHelper.GetDoctorById(result.appointment.DoctorId ?? 0);
                bsm.hospital = await HospitalApiRequestHelper.GetHospitalById(result.appointment.HospitalId ?? 0);
                bsm.scheduleData = await ScheduleApiRequestHelper.getScheduleDetail(result.appointment.ScheduleDataID ?? 0);
                bsm.pavm = result;
                return PartialView("_bookingSuccess", bsm);
            }
            else
            {
                return Json("Fail", JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult list(string msgrid=null)
        {
            ViewBag.msgrid = msgrid;
            return View("list");
        }


        public async Task<ActionResult> _bookedlist(string userid=null)
        {
            List<tbAppointment> appList = await BookingApiRequestHelper.getAppointments(userid);

            return PartialView("_bookedlist", appList);
        }


    }
}

CareMeBotWeb/Controllers/DoctorController.cs
using Data.Models;
using Data.ViewModels;
using Infra.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CareMeBotWeb.Controllers
{
    public class DoctorController : Controller
    {
        // GET: Doctor
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> _doctor(int doctorID)
        {
            DoctorSpecialityViewModel doctor = await DoctorApiRequestHelper.GetDoctorById(doctorID);
            return PartialView("_doctor", doctor);
        }


    }
}

CareMeBotWeb/Controllers/HospitalController.cs
using Core.Extensions;
using Data.Models;
using Data.ViewModels;
using Infra.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CareMeBotWeb.Controllers
{
    public class HospitalController : Controller
    {
        // GET: Hospital
        public ActionResult Index()
        {
            return View();
        }


        public async Task<ActionResult> _hospitalList(int doctorID, int hospitalID = 0, DateTime? AppointmentDate = null)
        {
            AppointmentDate = MyExtension.getLocalTime(DateTime.UtcNow);
            IEnumerable<HospitalSchedules> hospitalList = await HospitalApiRequestHelper.scheduledHospitalList(doctorID, hospitalID, AppointmentDate);
            return PartialView("_hospitalList", hospitalList);
        }




    }
}

CareMeBotWeb/Controllers/PatientController.cs
using Data.Models;
using Data.ViewModels;
using Infra.Helper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CareMeBotWeb.Controllers
{
    public class PatientController : Controller
    {
        // GET: Patient
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> _PatientForm(string FormType, int ID, int doctorid = 0,
            string doctorname = null, DateTime? appdate = null,
            DateTime? fromtime = null, DateTime? totime = null, 
            int scheduleid = 0, string MsgrID = null, string MsgrName=null)
        {
            ViewBag.doctorid = doctorid;
            ViewBag.doctorname = doctorname;
            ViewBag.appdate = appdate;
            ViewBag.fromtime = fromtime;
            ViewBag.totime = totime;
            ViewBag.scheduleid = scheduleid;
            tbPatient patient = new tbPatient();
            patient.MsgrID = MsgrID;
            patient.MsgrName = MsgrName;
            if (FormType == "Add")
            {
                return PartialView("_PatientForm", patient);
            }
            else
            {
                return null;
            }
        }


        public async Task<ActionResult> UpsertPatient(tbPatient patient, int doctorid = 0, 
            string doctorname = null, DateTime? appdate = null, DateTime? fromtime = null,
            DateTime? totime = null, int scheduleid = 0, int hospitalID=0)
        {
            PatientAppointmentViewModel shvm = new PatientAppointmentViewModel();
            shvm.appointment = new tbAppointment();
            shvm.appointment.DoctorId = doctorid;
            shvm.appointment.DoctorName = doctorname;
            string date = appdate.Value.ToShortDateString();
            string fromtimedate = fromtime.Value.ToShortTimeString();
            string appointmentdate = date + " " + fromtimedate;
            shvm.appointment.ScheduleDataID = scheduleid;
            shvm.appointment.AppointmentDateTime = DateTime.Parse(appointmentdate);
            shvm.appointment.HospitalId = hospitalID; //CareMeClient.Helper.CookieHelper.getstaffHospitalID();
            //      shvm.appointment.HospitalName = CareMeClient.Helper.CookieHelper.getstaffHospitalName();

            shvm.patient = patient;
            PatientAppointmentViewModel result = await BookingApiRequestHelper.UpsertPatient(shvm);
            if (result != null)
            {
                return Json("Success", JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json("Fail", JsonRequestBehavior.AllowGet);
            }
        }
    }
}

CareMeBotWeb/Views/Appointment/Index.cshtml
@{
    ViewBag.Title = "Appointment";
}
@section css{
    <style>
        .circle-loader {
            margin-bottom: 1.5em;
            border: 2px solid rgba(0, 0, 0, 0.2);
            border-left-color: #5cb85c;
            animation: loader-spin 1.2s infinite linear;
            position: relative;
            display: inline-block;
            vertical-align: top;
            border-radius: 50%;
            width: 11em;
            height: 11em;
        }

        .load-complete {
            -webkit-animation: none;
            animation: none;
            border-color: #5cb85c;
            transition: border 500ms ease-out;
        }

        @@keyframes loader-spin {
            0% {
                transform: rotate(0deg);
            }

            100% {
                transform: rotate(360deg);
            }
        }
    </style>



}

<div class="col-md-4 col-md-offset-4 col-xs-12 pa-0">
    <div id="div_doctor_holder">

    </div>

    <br />
    <h4 class="lh10"><i class="icon-info22"></i> Make an appointment</h4>
    <span class="text-muted mb-5">Check schedule for this doctor in these hospital</span>
    <br />
    <br />

    <div id="div_hospital_schedule_holder">

    </div>

    <br />
    <br />
</div>

@section scripts{
    <script type="text/javascript">
        var doctorID = "@ViewBag.doctorID";
        var hospitalID = 0;
        var msgrid = "@ViewBag.msgrid";
        var msgrname = "@ViewBag.msgrname";


        $(function () {
            bindDoctor();
            bindHospitals();
        });

        function bindDoctor() {
            $.ajax({
                cache: false,
                url: '@Url.Action("_doctor", "Doctor")',
                data: { doctorID: doctorID },
                beforeSend: function () {

                },
                success: function (result) {
                    $('#div_doctor_holder').empty().append(result);
                },
                complete: function () {
                }
            });
        }

        function bindHospitals() {
            $.ajax({
                cache: false,
                url: '@Url.Action("_hospitalList", "Hospital")',
                data: { doctorID: doctorID, hospitalID: hospitalID },
                beforeSend: function () {

                },
                success: function (result) {
                    $('#div_hospital_schedule_holder').empty().append(result);
                },
                complete: function () {
                }
            });
        }

        function showSchedules(e) {
            var hpid = $(e).attr('data-hospitalid');
            $('.hs_hide').addClass('hidden');
            $('.hs_show').removeClass('hidden');
            $('#div_hs_show_' + hpid).addClass('hidden');
            $('#div_hs_hide_' + hpid).removeClass('hidden');
        }

        function bindHospitalSchedule() {

        }

        function makebooking(e) {
            var doctorid = $(e).attr('data-doctorid');
            var doctorname = $(e).attr('data-doctorname');
            var appdate = $(e).attr('data-appdate');
            var fromtime = $(e).attr('data-fromtime');
            var totime = $(e).attr('data-totime');
            var scheduleid = $(e).attr('data-scheduleid');
            var date = $(e).attr('data-date');
            var hospitalID = $(e).attr('data-hospitalid');
            var displaydate = $(e).attr('data-displaydate');
            var displaytime = $(e).attr('data-displaytime');
            
            $('.pform').empty().hide();
            PatientForm("Add", 0, doctorid, doctorname, appdate, fromtime, totime, scheduleid, date,hospitalID , displaydate,displaytime);
        }

        function cancelBooking() {
            $('.pform').empty().hide();
            $('.datebtns').show();
        }

        function PatientForm(FormType, ID, doctorid, doctorname, appdate, fromtime, totime, scheduleid, date, hospitalID, displaydate,displaytime) {
            console.log('#pform_' + date);
            console.log("hid" + hospitalID);
            console.log(scheduleid);
;            $.ajax({
                cache: false,
                url: '@Url.Action("_PatientForm", "Patient")',
                data: { FormType: FormType, ID: ID, doctorid: doctorid, doctorname: doctorname, appdate: appdate, fromtime: fromtime, totime: totime, scheduleid: scheduleid, MsgrID:msgrid, MsgrName: msgrname },
                beforeSend: function () {

                },
                success: function (myData) {
                    $('#pform_' + date).empty().append(myData);
                    $('#pform_' + date).show();
                    $('.txt_date').empty().append(displaydate + " " + displaytime);

                    $('.datebtns').hide();
                    
                },
                complete: function () {



                    //$('#myModal').modal('show');
                    //bindSpecialityDD();

                    $('#PatientForm').submit(function (e) {
                        var doctorid = $('#doctorid').val();
                        var doctorname = $('#doctorname').val(); 
                        var appdate = $('#appdate').val();
                        var fromtime = $('#fromtime').val();
                        var totime = $('#totime').val();
                        var scheduleid = $('#scheduleid').val();
                        e.preventDefault();
                        $.ajax({
                            cache: false,
                            url: '@Url.Action("UpsertPatient", "Booking")',
                            type: "Post",
                            data: $(this).serialize() + "&doctorid=" + doctorid + "&doctorname=" + doctorname + "&appdate=" + appdate + "&fromtime=" + fromtime + "&totime=" + totime + "&scheduleid=" + scheduleid + "&hospitalID=" + hospitalID,
                            beforeSend: function () {
                                $('.btn').prop("disabled", true);
                            },
                            success: function (myData) {
                                if (myData != "Fail") {
                                    // window.location = '/Appointment/Success';
                                    $('#pform_' + date).empty().append(myData);
                                } else {
                                    alert("Booking process fail");
                                }
                                //$('#myModal').modal('hide');
                            },
                            complete: function () {
                                $('.btn').prop("disabled", false);

                            }
                        });
                    });

                }


            });

        }

    </script>
    
    
    
    }

CareMeBotWeb/Views/Appointment/Success.cshtml
@{
    ViewBag.Title = "Success";
}
@section css{
    <style>
        .circle-loader {
  margin-bottom: 1.5em;
  border: 2px solid rgba(0, 0, 0, 0.2);
  border-left-color: #5cb85c;
  animation: loader-spin 1.2s infinite linear;
  position: relative;
  display: inline-block;
  vertical-align: top;
  border-radius: 50%;
  width: 11em;
  height: 11em;
}

.load-complete {
  -webkit-animation: none;
  animation: none;
  border-color: #5cb85c;
  transition: border 500ms ease-out;
}
    
@@keyframes loader-spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
    </style>
   


    }

@*<div class="col-md-4 col-md-offset-4 col-xs-12 pa-0">
    <h2 class="text-green-700"><i class="icon-checkmark"></i> Booking Successful</h2>
    <small>You have successfully booked an appointment</small>

    <br /><br />
    <a href="/booking/list" class="btn btn-primary btn-rounded">View your bookings</a>
</div>*@

<div class="col-md-4 col-md-offset-4 col-xs-12 text-center pa-0">
    <h2>Asia Royal</h2>
    <img width="60" height="60" class="img-circle" src="https://kktstroage.azureedge.net/yammo/careme/default_doctor_photo.jpg"/>
    <h4 class="mb-0">Dr.Zaw Than Htun</h4>
    <span>M.B.S.S</span>
    <br /><br />
    <div class="circle-loader load-complete p-10">
        <h5 class="lh15 ">07:30 PM</h5>
        <h4 class="lh15 ">17 Nov 2018</h4>
        <hr class="m-5" />
        <h6 class="lh10">Booking No</h6>
        <h2 class="lh10 text-bold">100</h2>
    </div>
   
    <h5 class="lh15">Active</h5>
    <h5 class="lh20">2:hr 40:mins approximately to see doctor</h5>
    <h4 class="lh15"><span class="text-primary-300">43 has</span> been called</h4>
    <hr />
    <h5>Important Note</h5>
    <h6>Time mentioned above is estimated based on schedule set by doctor and updated in realtime 
    please note that it may be changed for some reasons and we suggest you to come to hospital ??? ahead</h6>
</div>